[package]
name = "waifu-calendar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
graphql_client = "0.13.0"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
time = { version = "0.3.31" }
tokio = { version = "1.35.1", features = ["full"] }
